### PR TITLE
Replace time-based login failure with loginAttempted bool

### LINKED ISSUE #120: Slow network connection causes unwanted behavior when logging in
- Since unsuccessful login message appears after 3s, it doesn't give enough time to try and log in on slow connections
  - I logged in successfully after some time, but not before the message told me it had failed
- Might need to add a longer delay and/or add a way to cancel the attempt (involving the WebView somehow) after that delay so this confusion doesn't happen

### PR DESCRIPTION
**Pull request by lsherwin10**
- Change loginAttempted bool when a login is attempted, regardless of success or failure
  - The view loads twice when created for some reason, which caused an immediate failure every time on the first load. I added a firstLoad state to detect this
- Converted errorMessage bool to a computed property since it was not a state that was used outside LoginPageSearchView, and it then automatically updates based on other boolean state changes
- Random code formatting improvements

### CODE REVIEW

File: DiveMeets/DiveMeets/Views/Login/LoginProfile.swift [hunk 1]
```diff
@@ -50,146 +52,154 @@ struct LoginProfile: View {
...
-                    let divers = diverData[0][0].slice(from: "Divers:", to: "Judging") ?? ""
-                    print(divers)
-                    if divers != "" {
-                        profileType = "Coach"
-                    } else {
-                        profileType = "Diver"
+        Group {
+            if profileType == "Diver" {
+                ZStack {
+                    GeometryReader { geometry in
```
Comment (spencerdearman) [inline DiveMeets/DiveMeets/Views/Login/LoginProfile.swift]: Do you need this in a geometryReader?

**Review by spencerdearman — APPROVED** [review]
Looks great! Just one question

File: DiveMeets/DiveMeets/Views/Login/LoginProfile.swift (hunk 1 above)
Comment (lsherwin10) [reply DiveMeets/DiveMeets/Views/Login/LoginProfile.swift]: I can't see why it would need to be, it doesn't look like it's doing anything there. Do you think it's needed for the BackgroundSpheres?

Comment (spencerdearman) [reply DiveMeets/DiveMeets/Views/Login/LoginProfile.swift]: I don't think that it is needed anymore, I think that the backgroundSpheres has its own geo. reader

Comment (lsherwin10) [reply DiveMeets/DiveMeets/Views/Login/LoginProfile.swift]: Got it, will fix
