### PR TITLE
Fix duplicate record problem (and other discovered bugs)

### LINKED ISSUE #43: Some meets show a meet results and meet info link in the database
To reproduce:
- Search "National" as the name and "2023" as the year (search is in "update-filter-choices" branch)
- There shuold be two entries for USA Diving National meets each with the same meet ID. One is info, the other is results

- Maybe we already discussed this, or I was supposed to fix it, but what do we want to happen here?

### PR DESCRIPTION
**Pull request by lsherwin10**
- Fixed meets appearing more than once in meet search
  - Issue with meet duplicates not being detected
  - Fixed by considering duplicates to be entries that share the same meet id, and then removing them before adding a new entry if they were of earlier meet type stages (upcoming < current < past)

- Note: We should observe closely over time to be sure it is working properly, as I made significant changes to the function of this feature, but I think making sure we have unique meet ids in the database is a safe bet

- To update your database:
  - Pull this branch and run it
  - Wait for indexing to complete on the Meet search page
  - Open the Tools menu page
  - Press the "Fix Dates" button and wait for a completion print statement
  - Press the "Drop Duplicates" button and wait for a completion print statement
- This should remove all the duplicates and prevent any further conflicts in the future

*** Need to change the ContentView back to displaying the ToolsMenu view before merge

### CODE REVIEW

File: DiveMeets/DiveMeets/MeetsDataController.swift [hunk 1]
```diff
@@ -112,11 +99,11 @@ class MeetsDataController: ObservableObject {
             if let type = type {
                 meet.meetType = Int16(type.rawValue)
             }
-            if let startDate = startDate {
-                meet.startDate = df.date(from: startDate)
+            if let startDate = startDate, let date = df.date(from: startDate) {
```
Comment (spencerdearman) [inline DiveMeets/DiveMeets/MeetsDataController.swift:102]: What is the df.date

**Review by spencerdearman — APPROVED** [review]
Looks good, just one question

File: DiveMeets/DiveMeets/MeetsDataController.swift (hunk 1 above)
Comment (spencerdearman) [reply DiveMeets/DiveMeets/MeetsDataController.swift:102]: Im going to run the tests that you said to above

Comment (lsherwin10) [reply DiveMeets/DiveMeets/MeetsDataController.swift:102]: df is a DateFormatter object, and calling df.date(from: String) converts a date String into a Date object using a provided date format string, which is assigned above. Since the format is not guaranteed to work (like if I provide a string that isn't in the expected format), then it can return nil, which is why it is in an if-let.

**Comment by lsherwin10** [comment]
Feel free to update ContentView back to ToolsMenu and squash when you're all finished if it's good to merge
